package io.github.hugrlab.acl.jdbc;

import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;

/**
 * A callable statement of an {@link AclConnection}: its text was prefixed by the connection's mode
 * when it was prepared (spec 006); here a {@code USE} is noticed at each execution and the results
 * are wrapped in {@link AclResultSet}.
 */
final class AclCallableStatement extends ForwardingCallableStatement<CallableStatement> {
	private final AclConnection connection;
	private final String sql;
	private final boolean use;

	AclCallableStatement(CallableStatement arrow, AclConnection connection, String sql) {
		super(arrow);
		this.connection = connection;
		this.sql = sql;
		this.use = AclSql.containsUse(sql);
	}

	private ResultSet wrap(ResultSet rs) {
		return AclResultSet.wrap(rs, this, connection.nestedJson());
	}

	@Override
	public ResultSet executeQuery() throws SQLException {
		return wrap(connection.call(use, delegate::executeQuery));
	}

	@Override
	public boolean execute() throws SQLException {
		return connection.call(use, delegate::execute);
	}

	@Override
	public int executeUpdate() throws SQLException {
		return connection.call(use, delegate::executeUpdate);
	}

	@Override
	public long executeLargeUpdate() throws SQLException {
		return connection.call(use, delegate::executeLargeUpdate);
	}

	@Override
	public int[] executeBatch() throws SQLException {
		return connection.call(use, delegate::executeBatch);
	}

	@Override
	public long[] executeLargeBatch() throws SQLException {
		return connection.call(use, delegate::executeLargeBatch);
	}

	// JDBC 4.3: the methods that take SQL text are refused on a prepared statement - its text is the prepared one

	@Override
	public ResultSet executeQuery(String sql) throws SQLException {
		throw AclPreparedStatement.textRefused("executeQuery(String)");
	}

	@Override
	public boolean execute(String sql) throws SQLException {
		throw AclPreparedStatement.textRefused("execute(String)");
	}

	@Override
	public boolean execute(String sql, int autoGeneratedKeys) throws SQLException {
		throw AclPreparedStatement.textRefused("execute(String, int)");
	}

	@Override
	public boolean execute(String sql, int[] columnIndexes) throws SQLException {
		throw AclPreparedStatement.textRefused("execute(String, int[])");
	}

	@Override
	public boolean execute(String sql, String[] columnNames) throws SQLException {
		throw AclPreparedStatement.textRefused("execute(String, String[])");
	}

	@Override
	public int executeUpdate(String sql) throws SQLException {
		throw AclPreparedStatement.textRefused("executeUpdate(String)");
	}

	@Override
	public int executeUpdate(String sql, int autoGeneratedKeys) throws SQLException {
		throw AclPreparedStatement.textRefused("executeUpdate(String, int)");
	}

	@Override
	public int executeUpdate(String sql, int[] columnIndexes) throws SQLException {
		throw AclPreparedStatement.textRefused("executeUpdate(String, int[])");
	}

	@Override
	public int executeUpdate(String sql, String[] columnNames) throws SQLException {
		throw AclPreparedStatement.textRefused("executeUpdate(String, String[])");
	}

	@Override
	public long executeLargeUpdate(String sql) throws SQLException {
		throw AclPreparedStatement.textRefused("executeLargeUpdate(String)");
	}

	@Override
	public long executeLargeUpdate(String sql, int autoGeneratedKeys) throws SQLException {
		throw AclPreparedStatement.textRefused("executeLargeUpdate(String, int)");
	}

	@Override
	public long executeLargeUpdate(String sql, int[] columnIndexes) throws SQLException {
		throw AclPreparedStatement.textRefused("executeLargeUpdate(String, int[])");
	}

	@Override
	public long executeLargeUpdate(String sql, String[] columnNames) throws SQLException {
		throw AclPreparedStatement.textRefused("executeLargeUpdate(String, String[])");
	}

	@Override
	public void addBatch(String sql) throws SQLException {
		throw AclPreparedStatement.textRefused("addBatch(String)");
	}

	@Override
	public ResultSet getResultSet() throws SQLException {
		return wrap(delegate.getResultSet());
	}

	@Override
	public ResultSet getGeneratedKeys() throws SQLException {
		return wrap(delegate.getGeneratedKeys());
	}

	@Override
	public ResultSetMetaData getMetaData() throws SQLException {
		ResultSetMetaData arrow = delegate.getMetaData();
		return arrow == null ? null
		                     : new AclResultSetMetaData(arrow, ResultTypes.of(delegate, arrow.getColumnCount()),
		                         connection.nestedJson());
	}

	@Override
	public Connection getConnection() {
		return connection;
	}

	@Override
	public <T> T unwrap(Class<T> iface) throws SQLException {
		return iface.isInstance(this) ? iface.cast(this) : delegate.unwrap(iface);
	}

	@Override
	public boolean isWrapperFor(Class<?> iface) throws SQLException {
		return iface.isInstance(this) || delegate.isWrapperFor(iface);
	}
}
