package io.github.hugrlab.acl.jdbc;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

/**
 * A statement of an {@link AclConnection}: its text sent as the connection's mode says
 * ({@code acl.mode}, spec 006), a {@code USE} noticed so the connection reads its catalog again, and
 * its results wrapped in {@link AclResultSet}.
 */
final class AclStatement extends ForwardingStatement<Statement> {
	private final AclConnection connection;

	AclStatement(Statement arrow, AclConnection connection) {
		super(arrow);
		this.connection = connection;
	}

	private String sent(String sql) {
		connection.noteStatement(sql);
		return connection.prefix(sql);
	}

	private ResultSet wrap(ResultSet rs) {
		return AclResultSet.wrap(rs, this, connection.nestedJson());
	}

	@Override
	public ResultSet executeQuery(String sql) throws SQLException {
		return wrap(delegate.executeQuery(sent(sql)));
	}

	@Override
	public boolean execute(String sql) throws SQLException {
		return delegate.execute(sent(sql));
	}

	@Override
	public boolean execute(String sql, int autoGeneratedKeys) throws SQLException {
		return delegate.execute(sent(sql), autoGeneratedKeys);
	}

	@Override
	public boolean execute(String sql, int[] columnIndexes) throws SQLException {
		return delegate.execute(sent(sql), columnIndexes);
	}

	@Override
	public boolean execute(String sql, String[] columnNames) throws SQLException {
		return delegate.execute(sent(sql), columnNames);
	}

	@Override
	public int executeUpdate(String sql) throws SQLException {
		return delegate.executeUpdate(sent(sql));
	}

	@Override
	public int executeUpdate(String sql, int autoGeneratedKeys) throws SQLException {
		return delegate.executeUpdate(sent(sql), autoGeneratedKeys);
	}

	@Override
	public int executeUpdate(String sql, int[] columnIndexes) throws SQLException {
		return delegate.executeUpdate(sent(sql), columnIndexes);
	}

	@Override
	public int executeUpdate(String sql, String[] columnNames) throws SQLException {
		return delegate.executeUpdate(sent(sql), columnNames);
	}

	@Override
	public long executeLargeUpdate(String sql) throws SQLException {
		return delegate.executeLargeUpdate(sent(sql));
	}

	@Override
	public long executeLargeUpdate(String sql, int autoGeneratedKeys) throws SQLException {
		return delegate.executeLargeUpdate(sent(sql), autoGeneratedKeys);
	}

	@Override
	public long executeLargeUpdate(String sql, int[] columnIndexes) throws SQLException {
		return delegate.executeLargeUpdate(sent(sql), columnIndexes);
	}

	@Override
	public long executeLargeUpdate(String sql, String[] columnNames) throws SQLException {
		return delegate.executeLargeUpdate(sent(sql), columnNames);
	}

	@Override
	public void addBatch(String sql) throws SQLException {
		delegate.addBatch(sent(sql));
	}

	@Override
	public ResultSet getResultSet() throws SQLException {
		return wrap(delegate.getResultSet());
	}

	@Override
	public ResultSet getGeneratedKeys() throws SQLException {
		return wrap(delegate.getGeneratedKeys());
	}

	@Override
	public Connection getConnection() {
		return connection;
	}

	@Override
	public <T> T unwrap(Class<T> iface) throws SQLException {
		return iface.isInstance(this) ? iface.cast(this) : delegate.unwrap(iface);
	}

	@Override
	public boolean isWrapperFor(Class<?> iface) throws SQLException {
		return iface.isInstance(this) || delegate.isWrapperFor(iface);
	}
}
